QUESTION_BANK = {
    "📊 Arrays": [
        "Find largest & smallest element",
        "Reverse an array",
        "Check if array is sorted",
        "Move all zeros to end",
        "Rotate array (left & right)",
        "Find second largest element",
        "Remove duplicates from sorted array",
        "Count frequency of elements",
        "Find missing number (1 to n)",
        "Find duplicate number",
        "Subarray with given sum",
        "Maximum subarray sum (Kadane's Algorithm)",
        "Merge two sorted arrays",
        "Intersection of two arrays",
        "Longest subarray with sum K",
        "Majority element (appears > n/2 times)",
    ],
    "🔤 Strings": [
        "Reverse a string",
        "Check palindrome",
        "Count vowels & consonants",
        "Anagram check",
        "First non-repeating character",
        "Frequency of characters",
        "Remove duplicate characters",
        "Longest word in a sentence",
        "Check substring",
        "Valid parentheses",
        "Reverse words in a sentence",
        "Check if two strings are rotations",
        "String compression (aaabb → a3b2)",
        "Convert lowercase to uppercase without built-in function",
    ],
    "🔍 Searching": [
        "Linear search",
        "Binary search",
        "First & last occurrence of element",
        "Search in rotated sorted array",
    ],
    "🔃 Sorting": [
        "Bubble sort",
        "Selection sort",
        "Insertion sort",
        "Merge sort",
        "Quick sort",
        "Sort 0s, 1s, 2s (Dutch National Flag)",
    ],
    "🔗 Linked List": [
        "Create a linked list",
        "Traverse linked list",
        "Insert at beginning and end",
        "Delete a node",
        "Reverse a linked list",
        "Find middle of linked list",
        "Detect loop (Floyd's cycle detection)",
        "Remove loop",
        "Merge two sorted linked lists",
        "Palindrome linked list",
    ],
    "📚 Stack": [
        "Implement stack using array",
        "Stack using list",
        "Check balanced parentheses",
        "Reverse string using stack",
        "Next greater element",
        "Stack using two queues",
        "Min stack",
        "Evaluate postfix expression",
    ],
    "🎫 Queue": [
        "Implement queue using array",
        "Queue using stack",
        "Circular queue",
        "Deque (double-ended queue)",
        "Reverse a queue",
        "First non-repeating character in stream",
    ],
    "#️⃣ Hashing": [
        "Frequency count using dictionary",
        "Find duplicate elements",
        "Two sum problem",
        "Subarray with zero sum",
        "Longest consecutive sequence",
        "Count pairs with given sum",
        "Majority element",
        "First repeating element",
    ],
    "🔄 Recursion": [
        "Factorial",
        "Fibonacci",
        "Reverse array using recursion",
        "Sum of digits",
        "Palindrome check using recursion",
        "Power of number",
        "Print all subsets",
        "Tower of Hanoi",
    ],
    "🌳 Trees": [
        "Binary tree traversal (Inorder, Preorder, Postorder)",
        "Height of tree",
        "Count leaf nodes",
        "Level order traversal",
        "Check if two trees are identical",
        "Binary Search Tree — insert & search",
    ],
    "🕸️ Graphs": [
        "Breadth First Search (BFS)",
        "Depth First Search (DFS)",
        "Number of connected components",
        "Detect cycle in graph",
    ],
    "➗ Math & Logic": [
        "Prime number check",
        "Count digits in a number",
        "Reverse a number",
        "Armstrong number",
        "GCD and LCM",
        "Power of two check",
        "Fibonacci series",
        "Swap numbers without temp variable",
        "Count trailing zeros in factorial",
    ],
}
